### ISSUE TITLE
Failed to process committed block  when use  version v.0.2.3

### ISSUE THREAD

**Issue by whyrucode** [persistenceOne/persistenceCore#104]
logs:

10:01AM INF committed state app_hash=B3C9230F2B6354AF99209B749CC3B34F94D3AE55FAB22F1AFEEE4A0B16DF5E41 height=1 module=state num_txs=0
10:01AM INF indexed block height=1 module=txindex
10:01AM INF Stopping queryMaj23Routine for peer module=consensus peer={"Data":{},"Logger":{}}
panic: Failed to process committed block (2:235D60A303BCC8185ACD1DB8C163F6DA422C0F1ACFD87D84D78A005268F1CCD9): wrong Block.Header.AppHash.  Expected B3C9230F2B6354AF99209B749CC3B34F94D3AE55FAB22F1AFEEE4A0B16DF5E41, got D6D5FB195D230E170C3B147EB48FA8D248D8CEB53772DF8994244F82669126F0

goroutine 126 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc002b78fc0, 0x0)
	/home/runner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/blockchain/v0/reactor.go:401 +0x1265
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart

how to fix it, look forward to your reply.

**Comment by puneet2019** [comment]
Hi, You should not start from height 1 with v0.2.3 binary. 
If you are to sync entire chain from genesis, start with v0.1.3 till the upgrade height, then switch to 0.2.3.
If you want things to be faster use [state sync](https://github.com/persistenceOne/awesome-persistence#state-sync), or download latest [snapshot](https://github.com/persistenceOne/awesome-persistence#snapshot) and sync from there.

**Comment by puneet2019** [comment]
it is not, really only if you are wanting to start a full node it makes sense to sync from v0.1.3, would just suggest to use snapshots or statesync.

Also if you are syncing from start, the chain will halt at the upgrade height automatically, that is when you switch binaries.

as backup you are supposed to protect `priv_validator_key.json` (if validator node) and entire `data` folder.
other things you can keep as is
