### ISSUE TITLE
Is the mainnet online?

### ISSUE THREAD

**Issue by Wangmmx** [persistenceOne/persistenceCore#16]
Are there external nodes? Mainnet or testnet.
Is the mainnet online now? I saw some transfer transactions on the browser, how can I get XPRT?

**Comment by puneet2019** [comment]
Yes, the main net is online, you can check [genesis transaction repo](https://github.com/persistenceOne/genesisTransactions) under core-1. 

link to explorer - [explorer.persistence.one](https://explorer.persistence.one)

you can buy xprt - on  [ascendex.com](https://ascendex.com/en/basic/cashtrade-spottrading/usdt/xprt)
for more information you can checkout our [website](https://persistence.one)

**Comment by Wangmmx** [comment]
Thanks  a lot!
I will buy some xprt later, and close the issue
