### ISSUE TITLE
47ing

### ISSUE THREAD

**Issue by faddat** [persistenceOne/persistenceCore#188]
there are some issues here, that should be addressed:

* I think that it's a better idea to use async-icq than the icq package currently being used in the persistence-sdk
* It is probably better to jump from 45 to 47 rather than using 46 in the middle
* need to refactor the proto files build system

**Comment by xlab** [comment]
Hey @faddat  👋 

> 1. I think that it's a better idea to use async-icq than the icq package currently being used in the persistence-sdk
Agreed, but as @puneet2019 said, this migration awaits until async-icq will be on the hub, I believe this is the place https://forum.cosmos.network/t/simple-ibc-query-support-with-async-icq/10568 where the discussion happens, right? Or is there any other way how this could benefit us without having it enabled on another chain?

> 2. It is probably better to jump from 45 to 47 rather than using 46 in the middle
We've decided to do 45 to 46 upgrade only for the testnet, to keep the ball rolling, while collecting crash reports and understanding the path of migration better. 47 requires a lot of refactoring which is currently is in progress. But beyond that, there are some state migrations that might be missing if we have the migration scope too broad.
So, while on the testnet we do 46, it gives us more time to understand the upgrade path better and prepare v45 -> v47 for the mainnet as advised.

> 3. need to refactor the proto files build system

Yes, partially [did](https://github.com/persistenceOne/persistence-sdk/blob/d754c6fb65609c4b8273bffe1d78c5ffec6e2980/x/lsnative/protocgen.sh) similar thing as part of the `x/lsnative` module, to rebuild forked versions of cosmos protos from v46.

**A question there** – is it safe to do regeneration using a [Docker container](https://github.com/iqlusioninc/liquidity-staking-module/blob/6dfb5ff5a1a6aa03d897ecd71ba32ed06083b1f2/Makefile#L103), or better keep the full tree of protos cloned in the repo using **buf** plus a buf manifest with checksums?

**Comment by xlab** [comment]
Re: 3. Using `ghcr.io/cosmos/proto-builder` for now
