### ISSUE TITLE
[Ledger support] Error: address  rejected

### ISSUE THREAD

**Issue by dualsystems** [persistenceOne/persistenceCore#25]
Hello, 
try add ledger keys,  but see address rejected. Use cosmos app.

persistenceCore keys add ledger  --ledger  
Error: address  rejected

**Comment by puneet2019** [comment]
hi,
ledger is only supported with --coin-type 118, since you will be using cosmos app for doing transactions.
`persistenceCore keys add ledger --ledger --coin-type 118` this should work

**Comment by puneet2019** [comment]
As I see, it is referenced it README.md, closing this issue [here , ledger support experimental](https://github.com/persistenceOne/persistenceCore#ledger-support-experimental)
