### ISSUE TITLE
Error/Typo in setup script

### ISSUE THREAD

**Issue by Anmol1696** [persistenceOne/persistenceCore#26]
# Overview
Error in `.script/setup.sh` [here](https://github.com/persistenceOne/persistenceCore/blob/master/.script/setup.sh). Line one seems to be a non existent bash script, at line 1.
```bash
./.setup.sh
...
```
Even after removing `.`, this would still be a recursive call to script `setup.sh` script, which is wrong.

# Potential Fix
Either `.setup.sh` is a deprecated bash script, or one of the other scripts should be the one that needs to be called.

**Comment by puneet2019** [comment]
Yes, it should be reset.sh. If you can also raise a PR, test the script and link this issue to it would be great.
