### ISSUE TITLE
Incorrect License info

### ISSUE THREAD

**Issue by Anmol1696** [persistenceOne/persistenceCore#46]
## Overview
License seems to be missing copyright information.
https://github.com/amaranthine-network/persistenceCore/blob/master/LICENSE#L189

### Note
Seems to be present in multiple repositories

**Comment by Anmol1696** [comment]
Any update on this @deepanshutr ?

**Comment by deepanshutr** [comment]
Hi Anmol, that appendix gives instructions as to how to add the copyright to the work(project files). We have added that in project files. This licence is not to be mutated as it is a recognized licence by github, all project details are captured by github at the top, for forked work also based on the licence type.

**Comment by puneet2019** [comment]
@Anmol1696  can add `2019 PERSISTENCE TECHNOLOGIES PTE. LTD.`
