### ISSUE TITLE
App does list for Nano S Plus

### ISSUE THREAD

**Issue by ericlavoie** [persistenceOne/persistenceCore#76]
In Ledger Live 2.40.2 Persistence is not listed as one of the App for a Nano S plus.

**Comment by puneet2019** [comment]
We have submitted the form and have updated the ledger app, it might be updated later, till then you can use cosmos ledger app, with keplr

**Comment by puneet2019** [comment]
https://github.com/cosmos/gaia/issues/1573 
has a fix after it is listed under nano S plus
