### ISSUE TITLE
is there a docker image avaliable?

### ISSUE THREAD

**Issue by lsdbitrue** [persistenceOne/persistenceCore#97]
I found this one https://hub.docker.com/r/persistenceone/persistencecore/tags

It has only latest tag, is it trustable?

**Comment by Anmol1696** [comment]
Yes. 
We are working on creating a github flow to push the docker images as well with more fine grained tags. But this is currently trusted docker image.

If you dont, can just build the image with
```
make docker-build DOCKER_TAG_NAME=local
```
This will create an image `persisitenceone/persisitencecore:local` image on your local system.
